# Generated by Django 4.1.2 on 2023-03-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lojas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAGO', 'Ja foi pago'), ('DEVENDO', 'Nao foi pago')], max_length=20)),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_credor', to='omieemprestimos.lojas')),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos_devedor', to='omieemprestimos.lojas')),
            ],
        ),
    ]
