# Generated by Django 4.1.2 on 2023-03-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omieemprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='valor',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
