# Generated by Django 4.1.7 on 2023-03-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omieemprestimos', '0002_emprestimos_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lojas',
            name='apikey',
        ),
        migrations.RemoveField(
            model_name='lojas',
            name='apisecret',
        ),
    ]
